spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/test #url
    username: root  #用户名
    password: djsy0zewg  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
